version: '3.9'

services:
  db:
    image: postgres:14.1-alpine
    restart: always
    container_name: Bantik
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - '5432:5432'
    volumes:
      - bantik:/var/lib/postgresql/data
volumes:
  bantik:
